import sys
import os
import pandas as pd
from datetime import datetime, timezone
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(r"d:\05_Quant\NOWTRAEDING")
sys.path.insert(0, str(PROJECT_ROOT))

from src.backtest_engine import BacktestEngine
from config import settings

def check_signals_and_vetoes():
    print("Analyzing signals and vetoes from March 3rd to June 16th...")
    
    start_dt = datetime(2026, 3, 3, tzinfo=timezone.utc)
    end_dt = datetime(2026, 6, 16, 23, 59, 59, tzinfo=timezone.utc)
    
    engine = BacktestEngine()
    
    # We will load data and run a custom check loop
    master_df = engine.load_and_prepare_data("XAUUSD")
    if master_df is None:
        print("Historical data not found.")
        return
        
    df = master_df[(master_df["available_time"] >= start_dt) & (master_df["available_time"] <= end_dt)]
    print(f"Total M15 bars loaded for period: {len(df)}")
    
    total_signals = 0
    ml_vetoed = 0
    approved_but_blocked_drawdown = 0
    approved_but_blocked_hourly = 0
    
    from src.signal_engine import Signal
    
    # Filter only first bar of each hour (where signals are evaluated)
    df_hour = df[df["available_time"].dt.minute == 0]
    print(f"Total Hourly bars evaluated: {len(df_hour)}")
    
    for _, row in df_hour.iterrows():
        signal = engine.signal_engine.evaluate(row)
        if signal in [Signal.BUY, Signal.SELL]:
            total_signals += 1
            
            # Check ML Gatekeeper Veto
            features = {
                "RSI_M15": row.get("RSI_M15"),
                "RSI_H1": row.get("RSI_H1"),
                "RSI_H4": row.get("RSI_H4"),
                "ADX": row.get("ADX"),
                "ATR": row.get("ATR"),
                "hour": row["available_time"].hour
            }
            
            if settings.ML_GATEKEEPER_ACTIVE and engine.ml_gatekeeper.is_ready:
                score = engine.ml_gatekeeper.score_trade(features, row["close"], row["available_time"].hour)
                if score is not None:
                    is_safe = engine.ml_gatekeeper.is_entry_safe(score)
                    if not is_safe:
                        ml_vetoed += 1
                        
    print("\n=== STATISTICS FROM MARCH 3 TO JUNE 16 ===")
    print(f"Total BUY/SELL signals generated by Technical Strategy: {total_signals}")
    print(f"Signals vetoed by ML Gatekeeper (Loss Threat too high):  {ml_vetoed} ({ml_vetoed/total_signals*100:.1f}% if signals > 0 else 0)")
    print(f"Signals that passed ML check (would have entered):       {total_signals - ml_vetoed}")

if __name__ == "__main__":
    check_signals_and_vetoes()
