"""
NowTrading 2.1 — ML Gatekeeper (Phase 2 Preview)
Uses XGBoost to predict if a signal is likely to result in a losing cycle.

This file provides the basic structure for the Phase 2 implementation.
"""

import pandas as pd
from typing import Dict, Any, Optional

try:
    import xgboost as xgb
except ImportError:
    xgb = None

from src.audit_logger import log_info, log_error
from config import settings


class MLGatekeeper:
    # Feature order must match training schema exactly
    _FEATURE_COLS = ['RSI_Delta', 'Volatility_Index', 'Session_Code', 'RSI_H1_Div', 'Trend_Vol_Ratio', 'RSI_M15', 'RSI_H1', 'RSI_H4', 'ADX', 'ATR', 'hour']

    def __init__(self, model_path: str = "src/ml/gatekeeper_v1.model"):
        self.model_path = model_path
        self.model = None
        self.is_ready = False
        
        if xgb is not None:
            self._load_model()
        else:
            log_error("XGBoost is not installed. ML Gatekeeper disabled.")

    def _load_model(self):
        """Loads the XGBoost model from disk if it exists."""
        try:
            self.model = xgb.Booster()
            self.model.load_model(self.model_path)
            self.is_ready = True
            log_info("✅ ML Gatekeeper model loaded successfully.")
        except Exception as e:
            log_error(f"Failed to load ML model: {e}")
            self.is_ready = False

    def train(self, data_path: str):
        """
        Train the XGBoost model using the training_data.csv generated by backtests.
        """
        if xgb is None:
            return False

        try:
            df = pd.read_csv(data_path)
            
            # Feature engineering matching score_trade / predict
            df['RSI_Delta'] = df['RSI_H4'] - df['RSI_M15']
            
            def get_approx_price(symbol: str) -> float:
                symbol = symbol.replace("m", "").upper()
                if "JPY" in symbol:
                    return 160.0
                if symbol in ["US30", "DJI"]:
                    return 39000.0
                if symbol in ["US100", "NDX"]:
                    return 19000.0
                if symbol in ["US500", "SPX"]:
                    return 5200.0
                if symbol in ["XAUUSD", "GOLD"]:
                    return 2330.0
                if symbol in ["BTCUSD", "BTC"]:
                    return 65000.0
                return 1.1

            df['Volatility_Index'] = df['ATR'] / df['symbol'].apply(get_approx_price)
            
            session_map = {"ASIA": 0, "EUROPE": 1, "US": 2, "OVERLAP_ASIA_EU": 3, "OVERLAP_EU_US": 4, "OFF": -1}
            df['Session_Code'] = df['session'].map(session_map).fillna(-1)
            df['RSI_H1_Div'] = (df['RSI_H1'] - 50.0).abs()
            df['Trend_Vol_Ratio'] = df['ADX'] * df['ATR']
            
            # Drop rows with missing features or labels
            df = df.dropna(subset=self._FEATURE_COLS + ['is_win'])
            
            X = df[self._FEATURE_COLS]
            y = 1 - df['is_win']  # 1 = LOSS_THREAT, 0 = WIN
            
            dtrain = xgb.DMatrix(X, label=y)
            
            # Basic hyperparameters
            params = {
                'max_depth': 4,
                'eta': 0.1,
                'objective': 'binary:logistic',
                'eval_metric': 'auc'
            }
            
            log_info(f"Training XGBoost Gatekeeper on {len(df)} samples...")
            self.model = xgb.train(params, dtrain, num_boost_round=100)
            
            import os
            os.makedirs(os.path.dirname(self.model_path), exist_ok=True)
            self.model.save_model(self.model_path)
            self.is_ready = True
            
            log_info(f"✅ Model trained and saved to {self.model_path}")
            return True
        except Exception as e:
            log_error(f"Error training model: {e}")
            return False

    def predict(self, features: Dict[str, float]) -> Optional[float]:
        """
        Predict the probability of a win (1.0 = 100% win, 0.0 = 100% loss).
        Returns None if model is not ready.
        Uses fast list-based DMatrix creation to avoid per-call DataFrame overhead.
        """
        if not self.is_ready or xgb is None:
            return None
            
        try:
            # Build feature vector directly — avoids creating a DataFrame per call
            row = [features.get(col) for col in self._FEATURE_COLS]
            if any(v is None for v in row):
                return None
            dtest = xgb.DMatrix([row], feature_names=self._FEATURE_COLS)
            prob = self.model.predict(dtest)[0]
            # Since model is trained on 1-is_win (LOSS_THREAT = 1), prob is probability of LOSS_THREAT
            return float(prob)
        except Exception as e:
            log_error(f"Prediction error: {e}")
            return None

    def score_trade(self, indicators: Dict[str, float], price: float, hour: int, session: str = "OFF") -> Optional[float]:
        """
        Calculates features and returns LOSS_THREAT score.
        """
        features = {
            'RSI_M15': indicators.get('RSI_M15'),
            'RSI_H1': indicators.get('RSI_H1'),
            'RSI_H4': indicators.get('RSI_H4'),
            'ADX': indicators.get('ADX'),
            'ATR': indicators.get('ATR'),
            'hour': hour
        }
        
        if any(v is None for v in features.values()):
            return None
            
        features['RSI_Delta'] = features['RSI_H4'] - features['RSI_M15']
        features['Volatility_Index'] = features['ATR'] / price if price > 0 else 0
        
        session_map = {"ASIA": 0, "EUROPE": 1, "US": 2, "OVERLAP_ASIA_EU": 3, "OVERLAP_EU_US": 4, "OFF": -1}
        features['Session_Code'] = session_map.get(session, -1)
        features['RSI_H1_Div'] = abs(features['RSI_H1'] - 50.0)
        features['Trend_Vol_Ratio'] = features['ADX'] * features['ATR']
        
        return self.predict(features)

    def should_veto(self, indicators: Dict[str, float], price: float, hour: int, threshold: float = 0.8, session: str = "OFF") -> bool:
        """
        Returns True if the trade should be VETOED (probability of LOSS_THREAT > threshold).
        """
        score = self.score_trade(indicators, price, hour, session)
        if score is None:
            return False  # Pass if model not available
            
        return score > threshold

    def is_entry_safe(self, ml_score: float) -> bool:
        """
        Returns True if the ML loss threat score is strictly below the entry safe threshold.
        """
        return ml_score < getattr(settings, "ML_ENTRY_SAFE_THRESHOLD", 0.25)

    def get_lot_multiplier(self, ml_score: float) -> float:
        """
        Returns the lot size multiplier based on 3-tier ML loss-threat score.

        Score < ML_LOT_BOOST_THRESHOLD  → HIGH CONFIDENCE → ×ML_LOT_BOOST_MULTIPLIER (e.g. 1.5)
        Score > ML_LOT_REDUCE_THRESHOLD → CAUTION         → ×ML_LOT_REDUCE_MULTIPLIER (e.g. 0.7)
        Otherwise                       → BASE ZONE       → ×1.0
        """
        if ml_score < getattr(settings, "ML_LOT_BOOST_THRESHOLD", 0.25):
            return getattr(settings, "ML_LOT_BOOST_MULTIPLIER", 1.5)
        elif ml_score > getattr(settings, "ML_LOT_REDUCE_THRESHOLD", 0.45):
            return getattr(settings, "ML_LOT_REDUCE_MULTIPLIER", 0.7)
        return 1.0

    def reload_model(self) -> bool:
        """
        Hot-reload the XGBoost model from disk.
        Called by daily_retrain.py after a successful retrain without restarting the bot.
        Returns True if reload was successful.
        """
        if xgb is None:
            return False
        self.is_ready = False
        self._load_model()
        return self.is_ready
